* Upgraded to release 0.2.0 * Improved error handling during initialization * #76: Retry mechanism for passwords/numbers * Bugfix #75: panicked at 'assertion failed: salt.len() == 16'